name: build and deploy
on:
 push:
   branches:
     - main

jobs:
 Deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Setup node
       uses: actions/setup-node@v2

     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
         aws-region: us-east-1

     - name: Run Athena Query
       uses: idealo/aws-athena-query-action@v1
       with:
        query-context: Catalog=AwsDataCatalog,Database=test
        query-string: |
          SELECT SUBSTRING('201', 1) as server_status, COUNT(*) as request_count
          FROM mycsv
          WHERE access_log LIKE '%201%'
          UNION

          SELECT SUBSTRING('404', 1) as server_status, COUNT(*) as request_count
          FROM mycsv
          WHERE access_log LIKE '%404%'
          UNION

          SELECT SUBSTRING('502', 1) as server_status, COUNT(*) as request_count
          FROM mycsv
          WHERE access_log LIKE '%502%'
          UNION

          SELECT SUBSTRING('500', 1) as server_status, COUNT(*) as request_count
          FROM mycsv
          WHERE access_log LIKE '%500%'
          UNION

          SELECT SUBSTRING('200', 1) as server_status, COUNT(*) as request_count
          FROM mycsv
          WHERE access_log LIKE '%200%'
          UNION

          SELECT SUBSTRING('304', 1) as server_status, COUNT(*) as request_count
          FROM mycsv
          WHERE access_log LIKE '%304%'
          UNION

          SELECT SUBSTRING('204', 1) as server_status, COUNT(*) as request_count
          FROM mycsv
          WHERE access_log LIKE '%204%';
        output-location: s3://wsi-atena-103-test/github-action-result/
        output-filename: Access_logs.csv
